spring.application.name=vastra-backend
spring.datasource.url=jdbc:mysql://localhost:3306/vastra_store
spring.datasource.username=root
spring.datasource.password=ajay@#$%32NM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
server.port=8081
